from __future__ import annotations

import argparse
from datetime import date
from typing import Any, Callable

from ..workflow import WorkflowState


def build_parser(settings: dict[str, Any], handlers: dict[str, Callable[..., Any]]) -> argparse.ArgumentParser:
    command_parser = argparse.ArgumentParser(prog="author-agent")
    command_parser.add_argument("--log-level", choices=["DEBUG", "INFO", "WARNING", "ERROR"], default=None)
    sub = command_parser.add_subparsers(dest="command", required=True)
    release = sub.add_parser("release")
    release.add_argument("--book", required=True)
    release.add_argument("--image", default="")
    release.add_argument("--date", default=date.today().isoformat())
    release.add_argument("--url", default="")
    release.add_argument("--published", action="store_true")
    release.add_argument("--dry-run", action="store_true")
    release.set_defaults(func=handlers["release"])
    evergreen = sub.add_parser("evergreen")
    evergreen.add_argument("--date", default=date.today().isoformat())
    evergreen.add_argument("--image", default="")
    evergreen.add_argument("--dry-run", action="store_true")
    evergreen.set_defaults(func=handlers["evergreen"])
    today = sub.add_parser("today")
    today.add_argument("--date", default="")
    today.add_argument("--window", type=int, default=settings["orchestrator"].get("window_days", 1))
    today.add_argument("--force", action="store_true")
    today.add_argument("--dry-run", action="store_true")
    today.set_defaults(func=handlers["today"])
    dashboard = sub.add_parser("dashboard")
    dashboard.add_argument("--date", default="")
    dashboard.set_defaults(func=handlers["dashboard"])
    rag = sub.add_parser("rag")
    rag_sub = rag.add_subparsers(dest="rag_command", required=True)
    ingest_posts = rag_sub.add_parser("ingest-posts")
    ingest_posts.add_argument("--file", required=True)
    ingest_posts.add_argument("--platform", choices=["facebook", "instagram", ""], default="")
    ingest_posts.add_argument("--source", default="")
    ingest_posts.set_defaults(func=handlers["rag_ingest_posts"])
    import_meta = rag_sub.add_parser("import-meta")
    import_meta.add_argument("--file", required=True)
    import_meta.add_argument("--platform", choices=["auto", "facebook", "instagram"], default="auto")
    import_meta.set_defaults(func=handlers["rag_import_meta"])
    ingest_book = rag_sub.add_parser("ingest-book")
    ingest_book.add_argument("--book", required=True)
    ingest_book.add_argument("--date", default="")
    ingest_book.add_argument("--source", default="")
    ingest_book.add_argument("--id", default="")
    ingest_book.add_argument("--no-analyze", action="store_true")
    ingest_book.set_defaults(func=handlers["rag_ingest_book"])
    search = rag_sub.add_parser("search")
    search.add_argument("query")
    search.add_argument("--top-k", type=int, default=8)
    search.add_argument("--kind", action="append", choices=["post", "book"])
    search.add_argument("--platform", action="append", choices=["facebook", "instagram"])
    search.set_defaults(func=handlers["rag_search"])
    check = rag_sub.add_parser("check")
    check.add_argument("--text", required=True)
    check.add_argument("--platform", required=True, choices=["facebook", "instagram"])
    check.set_defaults(func=handlers["rag_check"])
    rag_sub.add_parser("stats").set_defaults(func=handlers["rag_stats"])
    mark = rag_sub.add_parser("mark-approved")
    mark.add_argument("--file", required=True)
    mark.set_defaults(func=handlers["rag_mark_approved"])
    rag_sub.add_parser("sync-approved").set_defaults(func=handlers["rag_sync_approved"])
    sub.add_parser("migrate", help="Apply/verify durable database migrations").set_defaults(func=handlers["migrate"])
    quickstart = sub.add_parser("quickstart", help="Run the safe local end-to-end demo pipeline")
    quickstart.add_argument("--json", action="store_true")
    quickstart.set_defaults(func=handlers["quickstart"])
    eval_parser = sub.add_parser("eval", help="Run deterministic generated-content quality evaluation")
    eval_parser.add_argument("--json", action="store_true")
    eval_parser.set_defaults(func=handlers["eval"])
    visual = sub.add_parser(
        "analyze-pages", help="Extract page-level evidence; falls back to text-only without a vision provider"
    )
    visual.add_argument("--book", required=True)
    visual.add_argument("--max-pages", type=int, default=0)
    visual.set_defaults(func=handlers["analyze_visual"])
    workflow = sub.add_parser("workflow", help="Inspect and recover durable automation workflows")
    workflow_sub = workflow.add_subparsers(dest="workflow_command", required=True)
    create = workflow_sub.add_parser("create")
    create.add_argument("--book", default="")
    create.add_argument("--campaign", default="")
    create.add_argument("--platform", default="")
    create.add_argument("--state", choices=[s.value for s in WorkflowState], default=WorkflowState.INGESTED.value)
    create.add_argument("--text", default="")
    create.set_defaults(func=handlers["workflow_create"])
    status = workflow_sub.add_parser("status")
    status.add_argument("id")
    status.set_defaults(func=handlers["workflow_status"])
    transition = workflow_sub.add_parser("transition")
    transition.add_argument("id")
    transition.add_argument("state", choices=[s.value for s in WorkflowState])
    transition.add_argument("--reason", default="manual recovery")
    transition.set_defaults(func=handlers["workflow_transition"])
    reject = workflow_sub.add_parser("reject", help="Reject a pre-publication workflow permanently")
    reject.add_argument("id")
    reject.add_argument("--reason", required=True)
    reject.set_defaults(func=handlers["workflow_reject"])
    edit = workflow_sub.add_parser("edit", help="Edit a draft field while in review; factual recheck is required")
    edit.add_argument("id")
    edit.add_argument("--field", required=True)
    edit.add_argument("--value", required=True)
    edit.add_argument("--actor", default="")
    edit.set_defaults(func=handlers["workflow_edit"])
    queue = workflow_sub.add_parser("queue", help="List workflows waiting for human review")
    queue.add_argument("--book", default="")
    queue.add_argument("--platform", choices=["facebook", "instagram", ""], default="")
    queue.add_argument("--min-age-days", type=int, default=None)
    queue.add_argument("--max-age-days", type=int, default=None)
    queue.add_argument("--sort", choices=["age", "book", "platform"], default="age")
    queue.set_defaults(func=handlers["workflow_queue"])
    publish = sub.add_parser("publish", help="Publish or schedule an approved workflow through the configured provider")
    publish.add_argument("id")
    publish.add_argument("--platform", choices=["facebook", "instagram"], required=True)
    publish.add_argument("--text", required=True)
    publish.add_argument("--media-url", default="")
    publish.add_argument("--schedule-at", default="", help="ISO-8601 local/offset datetime")
    publish.set_defaults(func=handlers["publish"])
    sub.add_parser("publish-due", help="Resume and publish due deferred scheduled jobs").set_defaults(
        func=handlers["publish_due"]
    )
    metrics = sub.add_parser("metrics", help="Fetch and persist a published workflow's metrics")
    metrics.add_argument("id")
    metrics.add_argument("--platform", choices=["facebook", "instagram"], default="facebook")
    metrics.set_defaults(func=handlers["metrics"])
    campaign = sub.add_parser("campaign", help="Plan and inspect post-release social campaigns")
    campaign_sub = campaign.add_subparsers(dest="campaign_command", required=True)
    plan = campaign_sub.add_parser("plan", help="Create a multi-touch launch campaign")
    plan.add_argument("--book", required=True)
    plan.add_argument("--release-date", required=True)
    plan.add_argument("--platform", action="append", choices=["facebook", "instagram"])
    plan.add_argument("--create-workflows", action="store_true")
    plan.add_argument("--no-persist", action="store_true")
    plan.set_defaults(func=handlers["campaign_plan"])
    campaign_status = campaign_sub.add_parser("status", help="Inspect a persisted campaign")
    campaign_status.add_argument("id")
    campaign_status.set_defaults(func=handlers["campaign_status"])
    preflight = sub.add_parser("meta-preflight", help="Validate Meta credentials, target and media before live publish")
    preflight.add_argument("--platform", required=True, choices=["facebook", "instagram"])
    preflight.add_argument("--media-url", default="")
    preflight.set_defaults(func=handlers["meta_preflight"])
    return command_parser
